const Data = [
    {
        id: 1,
        title: 'Nitin',
        backgroundColor: '#eec8bf',
        category: 'Branding & Brand Management',
        location: 'Hydrabad, Telangana(Nationwide)',
        credits: '12 credits',
        time: '6m ago',
        questions: {
            question1: 'What is Your web design requiremen?',
            question2: 'What is Your web design requiremen?',
            question3: 'What is Your web design requiremen?',
            question4: 'What is Your web design requiremen?',
            question5: 'What is Your web design requiremen?',
        },
        answers: {
            answer1: 'Make Changes to my current website',
            answer2: 'Make Changes to my current website',
            answer3: 'Make Changes to my current website',
            answer4: 'Make Changes to my current website',
            answer5: 'Make Changes to my current website',

        },
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    },
    {
        id: 2,

        title: 'Hemant',
        category: 'Branding & Brand Management',
        location: 'Hydrabad, Telangana(Nationwide)',
        credits: '12 credits',
        time: '6m ago',
        questions: {
            question1: 'What is Your web design requiremen?',
            question2: 'What is Your web design requiremen?',
            question3: 'What is Your web design requiremen?',
            question4: 'What is Your web design requiremen?',
            question5: 'What is Your web design requiremen?',
        },
        answers: {
            answer1: 'Make Changes to my current website',
            answer2: 'Make Changes to my current website',
            answer3: 'Make Changes to my current website',
            answer4: 'Make Changes to my current website',
            answer5: 'Make Changes to my current website',

        },
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    },
    {
        id: 3,
        title: 'Vikas',
        category: 'Branding & Brand Management',
        location: 'Hydrabad, Telangana(Nationwide)',
        credits: '12 credits',
        time: '6m ago',
        questions: {
            question1: 'What is Your web design requiremen?',
            question2: 'What is Your web design requiremen?',
            question3: 'What is Your web design requiremen?',
            question4: 'What is Your web design requiremen?',
            question5: 'What is Your web design requiremen?',
        },
        answers: {
            answer1: 'Make Changes to my current website',
            answer2: 'Make Changes to my current website',
            answer3: 'Make Changes to my current website',
            answer4: 'Make Changes to my current website',
            answer5: 'Make Changes to my current website',

        },
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    },
    {
        id: 4,
        title: 'Sunil',
        category: 'Branding & Brand Management',
        location: 'Hydrabad, Telangana(Nationwide)',
        credits: '12 credits',
        time: '6m ago',
        questions: {
            question1: 'What is Your web design requiremen?',
            question2: 'What is Your web design requiremen?',
            question3: 'What is Your web design requiremen?',
            question4: 'What is Your web design requiremen?',
            question5: 'What is Your web design requiremen?',
        },
        answers: {
            answer1: 'Make Changes to my current website',
            answer2: 'Make Changes to my current website',
            answer3: 'Make Changes to my current website',
            answer4: 'Make Changes to my current website',
            answer5: 'Make Changes to my current website',

        },
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    },
    {
        id: 5,
        title: 'Ajay',
        category: 'Branding & Brand Management',
        location: 'Hydrabad, Telangana(Nationwide)',
        credits: '12 credits',
        time: '6m ago',
        questions: {
            question1: 'What is Your web design requiremen?',
            question2: 'What is Your web design requiremen?',
            question3: 'What is Your web design requiremen?',
            question4: 'What is Your web design requiremen?',
            question5: 'What is Your web design requiremen?',
        },
        answers: {
            answer1: 'Make Changes to my current website',
            answer2: 'Make Changes to my current website',
            answer3: 'Make Changes to my current website',
            answer4: 'Make Changes to my current website',
            answer5: 'Make Changes to my current website',

        },
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    },
    {
        id: 6,
        title: 'Sagar',
        category: 'Branding & Brand Management',
        location: 'Hydrabad, Telangana(Nationwide)',
        credits: '12 credits',
        time: '6m ago',
        questions: {
            question1: 'What is Your web design requiremen?',
            question2: 'What is Your web design requiremen?',
            question3: 'What is Your web design requiremen?',
            question4: 'What is Your web design requiremen?',
            question5: 'What is Your web design requiremen?',
        },
        answers: {
            answer1: 'Make Changes to my current website',
            answer2: 'Make Changes to my current website',
            answer3: 'Make Changes to my current website',
            answer4: 'Make Changes to my current website',
            answer5: 'Make Changes to my current website',

        },
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    },
    {
        id: 7,
        title: 'Dhien',
        category: 'Branding & Brand Management',
        location: 'Hydrabad, Telangana(Nationwide)',
        credits: '12 credits',
        time: '6m ago',
        questions: {
            question1: 'What is Your web design requiremen?',
            question2: 'What is Your web design requiremen?',
            question3: 'What is Your web design requiremen?',
            question4: 'What is Your web design requiremen?',
            question5: 'What is Your web design requiremen?',
        },
        answers: {
            answer1: 'Make Changes to my current website',
            answer2: 'Make Changes to my current website',
            answer3: 'Make Changes to my current website',
            answer4: 'Make Changes to my current website',
            answer5: 'Make Changes to my current website',

        },
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
    },
]

export default Data;